apiVersion: network-simulator.patriot-framework.io/v1
kind: Device
metadata:
  name: device-sample
spec:
  network_name: network-example
  service_spec:
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
  podTemplate:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
        - name: hello-kubernetes
          image: paulbouwer/hello-kubernetes:1.8
          ports:
            - containerPort: 8080