apiVersion: network-simulator.patriot-framework.io/v1
kind: Device
metadata:
  name: device-generator-sample
spec:
  networkName: network-example
  deviceIngressPorts:
    - deviceName: device-generator-listener-sample
      networkName: network-example1
      networkPolicyPorts:
        - protocol: UDP
          port: 5683
  deviceEgressPorts:
    - deviceName: device-generator-listener-sample
      networkName: network-example
      networkPolicyPorts:
        - protocol: UDP
          port: 5683
  networkPolicySpec:
    podSelector: {}
    ingress:
      - from:
          -  ipBlock:
              cidr: 192.168.49.1/24
    policyTypes:
      - Ingress
  serviceSpec:
    type: NodePort
    ports:
      - protocol: UDP
        port: 5683
        targetPort: 5683
        nodePort: 30007
  podSpec:
    containers:
      - name: patriot-data-generator-runner
        image: jsmadis/patriot-data-generator-runner:latest
        ports:
          - containerPort: 5683
            protocol: UDP
        env:
          - name: PATRIOT_DATA_GENERATOR_DEVICE_FILE
            value: /var/test.json