apiVersion: network-simulator.patriot-framework.io/v1
kind: Device
metadata:
  name: device-sample
spec:
  active: true
  network_name: network-example
  podTemplate:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
        - name: hello-kubernetes
          image: paulbouwer/hello-kubernetes:1.8
          ports:
            - containerPort: 8080